### ISSUE TITLE
admin项目启动报错，缺dsl模板文件

### ISSUE THREAD

**Issue by LuZiZhang** [didi/KnowSearch#18]
1.arius-admin-persistence模块的dsl模板缺失：
IndexTemplateValueRecordEsDao/getRecordByLogicTemplateId
IndexTemplateHealthDegreeRecordDao/getRecordByLogicTemplateId

2.arius-admin-persistence模块的dsl模板名称和常量不一致：
![image](https://user-images.githubusercontent.com/19646688/197661660-74253eb8-3e31-4dcb-87ca-0bf41f411a10.png)
ES的大小写问题。

**Comment by zhangliangboy** [comment]
新版本发布，问题已解决
