### ISSUE TITLE
使用DSL查询，切换集群没效果

### ISSUE THREAD

**Issue by HungryMouse** [didi/KnowSearch#52]
![image](https://user-images.githubusercontent.com/28881234/229668496-4d890637-0bc1-460a-a5b6-5b03a165432b.png)

![image](https://user-images.githubusercontent.com/28881234/229668516-5fdd0fec-a21e-40c7-9dc7-c9cc8c8cece9.png)

服务是用0.3.1.2版本的离线安装包搭建的，搭建过程中出现过一次nginx端口占用的报错，修改端口后解决，无其他报错

**Comment by zhangliangboy** [comment]
这个问题部署安装的时候，配置文件和初始化脚本有误，已经修复，可以下载最新的安装包体验
