### ISSUE TITLE
KnowSearch 用户认证安全风险修复

### ISSUE THREAD

**Issue by zhangliangboy** [didi/KnowSearch#86]
[ad1aa7b3-ecee-44b0-a22a-80917ca0fe71.pdf4398935202801712312.pdf](https://github.com/didi/KnowSearch/files/12135597/ad1aa7b3-ecee-44b0-a22a-80917ca0fe71.pdf4398935202801712312.pdf)

**Comment by PenceXie** [comment]
已修复
