### ISSUE TITLE
KnowSearch服务器搭建配置推荐

### ISSUE THREAD

**Issue by lyhonglingjin** [didi/KnowSearch#90]
管理30套ES集群，节点数300个，数据量大概100T，分片数8W，大概需要什么样的服务器配置？
比如：内存，CPU，磁盘 的配置。

**Comment by huqidong** [comment]
主要4个服务：
1.）mysql 服务：单实例，生产环境建议主备 HA。单实例配置：最低4gb内存，推荐 8gb内存，cpu 4c+ 即可，如采用磁盘，建议 innodbbuffersize 设置尽量大一点。
2.）admin 服务：3 实例。单实例配置：配置：cpu 4c+，内存 16gb，普通磁盘即可
3.）gateway 服务：3 实例。单实例配置：配置：cpu 4c+，内存 16gb+，普通磁盘即可
4.）元数据 elasticsearch 服务：3 实例。单实例配置：以数据存储一个月为例，cpu 8c+，内存 64gb+，硬盘 ssd 2t+
